set1 = {'A','P','P','L','E'}
set2 = set(list('PINEAPPLE'))
set3 = set(list('BANANA'))
print(set1)
print(set2)
print(set3)
set1.add("k")
print(set1)
set1.remove("k")
print(set1)
print(set1 | set3)
print(set1 & set3)
print(set1 ^ set3)
print(len(set1|set3))
set1.add("hi")
set1.add(3.14)
set3.add(True)
print(set1,set3)
