from common.const import MAX_CONCURRENT_JOBS,PI,GRAVITY
print(PI)
print(MAX_CONCURRENT_JOBS)
print(GRAVITY)

PI *=2
MAX_CONCURRENT_JOBS +=100
GRAVITY = GRAVITY - 1
print(PI)
print(MAX_CONCURRENT_JOBS)
print(GRAVITY)
